sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"

addons:
  chrome: stable
script: true
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install
